fix(flake): flake outputs wrapperModules -> wrappedModules
Yeah... My apologies for any inconvenience. Use mass find and replace.

The confusion between `wlib.wrapperModules` and flake
`outputs.wrapperModules` and the not knowing what to export the
importable ones as has to end.

`wrapperModules` vs `wrappedModules`

Guess which you can import and which you can't (you can't import the
wrapped ones)

Much better.

In the future when the deprecation warning is removed, rather than
removing the output, they will be replaced by the unevaluated wrapper
modules, so that it has`outputs.wrapperModules` and
`outputs.wrappedModules` outputs.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,16 +17,16 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Merge main into PR branch
-        if: github.event_name == 'pull_request'
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          git fetch origin main
-          if ! git merge origin/main; then
-            echo "Merge failed due to conflicts. Please rebase your branch on main."
-            exit 1
-          fi
+      # - name: Merge main into PR branch
+      #   if: github.event_name == 'pull_request'
+      #   run: |
+      #     git config user.name "GitHub Actions"
+      #     git config user.email "actions@github.com"
+      #     git fetch origin main
+      #     if ! git merge origin/main; then
+      #       echo "Merge failed due to conflicts. Please rebase your branch on main."
+      #       exit 1
+      #     fi
 
       - name: Install Nix
         uses: DeterminateSystems/nix-installer-action@main
@@ -35,4 +35,4 @@ jobs:
       #   uses: DeterminateSystems/magic-nix-cache-action@main
 
       - name: Run checks
-        run: nix flake check -Lv --log-format bar-with-logs
+        run: nix flake check -Lvv --log-format bar-with-logs
